### PR TITLE
Changing variable to resolve issue with Ansible 2.9

### PR DESCRIPTION
**Pull request by hiero-nymus**
I've encountered the same problem as @harrydevine with RHEL8 and **Ansible 2.9.** For this reason I propose a change of one variable.

### CODE REVIEW

**Comment by ahuffman** [comment]
@hiero-nymus I'm assuming you've fully tested this change out.  I unfortunately do not have a Satellite6 environment to vet this against any longer.  There were a lot of changes to Ansible in the last couple of years as I'm aware, as well as the move to a full Python3 implementation.  

If you reply it was tested and functions I will merge.

**Comment by hiero-nymus** [comment]
@ahuffman, yes we've fixed this error on our Satellite6 environment and it's running. This is why I've proposed this changed via pull request.

**Comment by ahuffman** [comment]
@hiero-nymus thanks for the contribution!

**Comment by ahuffman** [comment]
Version 1.0.5 is live now: https://galaxy.ansible.com/ahuffman/satellite6_manage_content_views

**Pull request merged**
